kind: pipeline
name: pipeline
steps:
- name: publish
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: swimdock-${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]

- name: publish tag
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: swimdock-${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    event:
      - tag

- name: deploy api
  image: quving/drone-rancher-cicd:latest
  settings:
    stamp: ${DRONE_COMMIT}
    kubernetes_deployment: swimdock-api,swimdock-worker
    kubernetes_namespace: testing
    rancher_url:
      from_secret: rancher_url
    rancher_token:
      from_secret: rancher_token
    rancher_context:
      from_secret: rancher_context
  when:
    status: [ success ]
    branch: [ master ]
